# Generated by Django 5.2.1 on 2026-03-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trusted_devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trusteddevice",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-defined label for this device (e.g. 'Work Laptop').",
                max_length=255,
            ),
        ),
    ]
