# Generated by Django 5.2.1 on 2026-04-26 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trusted_devices", "0002_add_device_name_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trusteddevice",
            name="last_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Most recently observed IP address. Compared against incoming requests to detect concurrent-session hijacks.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="can_delete_other_devices",
            field=models.BooleanField(
                default=True,
                help_text="Whether this device can delete other devices. Override default via TRUSTED_DEVICE['DEFAULT_CAN_DELETE_OTHER_DEVICES'].",
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="can_update_other_devices",
            field=models.BooleanField(
                default=True,
                help_text="Whether this device can update settings for other devices. Override default via TRUSTED_DEVICE['DEFAULT_CAN_UPDATE_OTHER_DEVICES'].",
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="ip_address",
            field=models.GenericIPAddressField(
                help_text="IP address of the device when first registered."
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["user", "-last_seen"], name="trusted_dev_user_id_58036d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["last_seen"], name="trusted_dev_last_se_7f14d2_idx"
            ),
        ),
    ]
